services:
  dpms-web:
    image: isresearch/dpms-web:latest
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 5s
    restart: unless-stopped
